min_os_version: 1.3.8
name: Anx Calibre Manager
package: community.lazycat.app.anx-calibre-manager
version: 1.13.5
description: "一个现代化的、移动端优先的 Web 应用，用于管理您的电子书库，可与 Calibre 集成，并为您的 Anx-reader 兼容设备提供个人 WebDAV 服务器。"
homepage: https://github.com/ptbsare/anx-calibre-manager
author: ptbsare
application:
  subdomain: anx
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://anx-calibre-manager-aio:5000/

    - location: /
      domain_prefix: calibre
      backend: http://anx-calibre-manager-aio:8080/

    - location: /
      domain_prefix: cwa
      backend: http://calibre-web-automated:8083/

services:
  anx-calibre-manager-aio:
    # ghcr.io/ptbsare/anx-calibre-manager:aio-1.13.5
    image: registry.lazycat.cloud/czyt/ptbsare/anx-calibre-manager:1bc6050cdc71caed
    container_name: anx-calibre-manager-aio
    ports:
      - "5000:5000"
      - "8080:8080"
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/var/webdav:/webdav
      - /lzcapp/var/library:/"Calibre Library"
    environment:
      - CALIBRE_URL=https://calibre-{{.S.AppDomain}}
      - CALIBRE_USERNAME={{.U.calibre_username}}
      - CALIBRE_PASSWORD={{.U.calibre_password}}

  calibre-web-automated:
    # ghcr.io/crocodilestick/calibre-web-automated:latest
    image: registry.lazycat.cloud/czyt/crocodilestick/calibre-web-automated:cd0bd06d4b15ffec
    container_name: calibre-web-automated
    ports:
      - "8083:8083"
    binds:
      - /lzcapp/var/library:/calibre-library
      - /lzcapp/var/cwa-config:/config
    environment:
      - PUID=1000
      - PGID=1000

unsupported_platforms:
  - ios
  - tvos
  - android

locales:
  zh:
    name: "Anx Calibre Manager"
    description: "一个现代化的、移动端优先的 Web 应用，用于管理您的电子书库，可与 Calibre 集成，并为您的 Anx-reader 兼容设备提供个人 WebDAV 服务器。 "
  en:
    name: "Anx Calibre Manager"
    description: "A modern, mobile-first web application to manage your ebook library, integrating with Calibre and providing a personal WebDAV server for your Anx-reader compatible devices."
