package: community.lazycat.app.anx-calibre-manager
version: 1.13.6
name: Anx Calibre Manager
description: "一个现代化的、移动端优先的 Web 应用，用于管理您的电子书库，可与 Calibre 集成，并为您的 Anx-reader 兼容设备提供个人 WebDAV 服务器。"
min_os_version: 1.5.0
homepage: https://github.com/ptbsare/anx-calibre-manager
author: ptbsare

unsupported_platforms:
  - ios
  - tvos
  - android

locales:
  zh:
    name: "Anx Calibre Manager"
    description: "一个现代化的、移动端优先的 Web 应用，用于管理您的电子书库，可与 Calibre 集成，并为您的 Anx-reader 兼容设备提供个人 WebDAV 服务器。"
  en:
    name: "Anx Calibre Manager"
    description: "A modern, mobile-first web application to manage your ebook library, integrating with Calibre and providing a personal WebDAV server for your Anx-reader compatible devices."
